### ISSUE TITLE
yaml and python data models don't agree for Deme objects

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#117]
In yaml, the `demes:` block contains mappings from a deme `id` to the deme's attributes.
```
demes:
  A:
    initial_size: 100
  B:
    initial_size: 100
```
In python though, our data model is that the `Graph.demes` is a `list of Deme`, with the `id` of the deme as an attribute of each `Deme` object in the list. We could change the python data model, but then the `Deme` class doesn't have an `id`.

Or should we instead change the spec for the data model so that we must write yaml like this?
```
demes:
  - id: A
    initial_size: 100
  - id: B
    initial_size: 100
```

Or we could have different data models in our spec compared with python. Then the json/yaml (de)serialisation process needs to translate between the two. (`load()` and `asdict_compact()` already do this, `asdict()` does not.)

**Comment by grahamgower** [comment]
We also have in the yaml:
```
migrations:
  symmetric:
  - demes: foo, bar
    time: 10
    rate: 1e-4
  asymmetric:
  - source: foo
    dest: bar
    time: 20
    rate: 1e-5
```
Versus in python where we translate all symmetric migrations into asymmetric migrations, and just have a single `migration` attribute.

**Comment by jeromekelleher** [comment]
I think we should change the yaml so it looks like 
```yaml
demes:
  - id: A
    initial_size: 100
  - id: B
    initial_size: 100
```

If we make the id attribute mandatory, then I think the readability difference is very minor and it simplifies the data model a lot.

The symmetric vs asymmetric migration thing is trickier, it's not clear what the right thing to do is. However, I think a good goal is to ensure that users don't have to write down the same migration rate twice in the YAML format. Would it be a big complication to have both types of migration in the ``Graph`` class?
