### ISSUE TITLE
vocabulary for demes

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#121]
I think we need to settle on a clear and consistent vocabulary for both the spec and our documentation. Here's a start, feel free to suggest different names:
 * **demes graph** - an object that conforms to the schema of our data model. This could be in reference to a specific implementation of a demographic model. E.g. the Gutenkunst et al. OOA demes graph. This does not specify which format/encoding the graph is in. In the context of our documentation, and within the code, we can probably drop the 'demes' prefix when there's no chance of confusion.
* **graph encoding** - the format the graph is in. This could be an interchange format like YAML/JSON, or a python `demes.Graph` object, or some other in memory data structure such as nested dictionaries/lists.
* **compact graph** - a demes graph with redundant information excluded. Users will typically write their yaml files as a compact demes graph.
* **redundant graph** - a demes graph with all the redundant information included. A `demes.Graph` object is an example of a redundant demes graph. One can also serialise all the redundant info to a YAML or JSON encoded file. This might then be used by non-python applications that don't want to deal with compact demes graphs themselves.

**Comment by jeromekelleher** [comment]
Sounds good, thanks @grahamgower. Can you expand a bit on what you mean by redundancy here?

**Comment by grahamgower** [comment]
+1 for 'fully qualified' instead of redundant. I don't have a list of the rules (these are just in the python code right now). But I've put an example below. I'm guessing we'll need two different schemas, which differ only in regard to which fields are optional (I *think* json schema makes it easy to do this without writing both schemas manually).

**Compact**
```yaml
# examples/bottleneck.yml
description: A single-population bottleneck model. Also tests a finite start_time.
generation_time: 1
time_units: generations
demes:
  our_population:
    description: Bottleneck population using epochs
    start_time: 10000
    epochs:
    - initial_size: 1e4
      end_time: 500
    - initial_size: 1e2
      end_time: 100
    - initial_size: 1e4
      end_time: 0
```
**Fully qualified**
```yaml
# python -c "from demes import *; dump(load('examples/bottleneck.yml'), '/dev/stdout', compact=False)"
description: A single-population bottleneck model. Also tests a finite start_time.
time_units: generations
generation_time: 1
demes:
  our_population:
    description: Bottleneck population using epochs
    epochs:
    - start_time: 10000
      end_time: 500
      initial_size: 10000.0
      final_size: 10000.0
      size_function: constant
    - start_time: 500
      end_time: 100
      initial_size: 100.0
      final_size: 100.0
      size_function: constant
    - start_time: 100
      end_time: 0
      initial_size: 10000.0
      final_size: 10000.0
      size_function: constant
    start_time: 10000
    end_time: 0
```

Also, maybe we should use a different term to 'compact', because the JSON python docs use that term to refer to a whitespace-impoverished file (as opposed to nicely pretty-printed). I think I'll change `demes` to output the compact, non-pretty-printed JSON by default. This probably saves on bytes, and users can easily pipe that through `python -c json.tool` to pretty print it.
