### ISSUE TITLE
Dealing with ambiguously defined demographic models

### ISSUE THREAD

**Issue by apragsdale** [grahamgower/demes#46]
In some cases, a demographic model could be perfectly valid but ambiguous. For example, take this demography with multiple pulse (MassMigration) events that occur at the same time:

```YAML
description: Ambiguous model with multiple pulses to same deme at same time.
time_units: generations
demes:
  ancestral:
    description: root deme
    end_time: 100
    initial_size: 1000
  deme1:
    description: deme one
    ancestors: ancestral
    initial_size: 1000
  deme2:
    description: deme two
    ancestors: ancestral
    initial_size: 1000
  deme3:
    description: deme three
    ancestors: ancestral
    initial_size: 1000
pulses:
  - time: 10
    source: deme1
    dest: deme3
    proportion: 0.2
  - time: 10
    source: deme2
    dest: deme3
    proportion: 0.3
````

In this example, `deme1` and `deme2` both pulse to `deme3` at the same time. If we apply the events in one order (`deme1` then `deme2`), we get resulting ancestry proportions of (0.14, 0.3, 0.56), and in the other order, proportions would be (0.2, 0.24, 0.56). (And maybe neither of these are what the implementer intended: maybe they wanted (0.2, 0.3 0.5).) This is a problem: a big point of this effort is to make demography description unambiguous!

Currently there is no way in `demes` to specify the order of these events. It would just end up being however python decides to sort the dictionary values of the pulses. There are a few solutions:

1. when such an ambiguous demography is loaded or implemented (maybe at the `get_demographic_events()` step), we generate a warning or an error that the demography is ambiguous, point to the elements that are ambiguous, and say it is not a valid demography. Point to docs on how to fix this issue. In this case, a solution is to use the `admix` event, which requires defining a new deme, but removes the ambiguity.
2. decide on some rule about the order that pulse events occurring at the same time with the same dest get sorted, perhaps alphabetically by source deme name. I like this less than (1), because it forces the user to remember what that rule is and maybe recalculate admixture proportions to get the desired outcome.

**Comment by apragsdale** [comment]
Just to follow up, the unambiguous way to define this model might then be something like this:

```YAML
description: Ambiguous model with multiple pulses to same deme at same time.
time_units: generations
demes:
  ancestral:
    description: root deme
    end_time: 100
    initial_size: 1000
  deme1:
    description: deme one
    ancestors: ancestral
    initial_size: 1000
  deme2:
    description: deme two
    ancestors: ancestral
    initial_size: 1000
  deme3_pre_admix:
    description: deme three before admixture
    ancestors: ancestral
    initial_size: 1000
    end_time: 10
  deme3:
    description: admixed deme three
    ancestors: deme1, deme2, deme3_pre_admix
    proportions: 0.2, 0.3, 0.5
    start_time: 10
    initial_size: 1000
```

**Comment by grahamgower** [comment]
I like the idea of doing both 1 and 2. I.e. having a warning that this is ambiguous, but also provide well-defined behaviour. We could always change the warning to an error in the future.

I think current behaviour is to depend on the order in which the pulse events are specified. This seems more reasonable to me than the obvious alternatives (e.g. sorting based on deme id). But maybe there are other policies that make sense? We could automatically change the pulse proportions to match the behaviour in your second example---but I don't like this because altering the time by some epsilon then changes the behaviour.

**Comment by molpopgen** [comment]
I'm clearly missing something.  I don't see the ambiguity?  The pulses are at the same time, and so I read that model as 0.2, 0.3, 0.5 for the ancestry of deme 3.

**Comment by apragsdale** [comment]
@molpopgen Thinking forwards in time, if they are applied sequentially, say deme1 first, then the intermediate ancestry is 0.2/0.8. Then if you have 30% admixture from deme2, you'd have 0.2*(1-0.3) / 0.3 / 0.8 * (1-0.3) = 0.14 / 0.3 / 0.56 ancestry proportions. The other order has a different result.

A third option would be to say, if there are multiple pulses at once, we just treat it like an admixture event with proportions (0.2, 0.3, 1-0.2-0.3), which then gets placed in deme3. That would avoid having to decide on some arbitrary sorting, and would be easy to document.

**Comment by apragsdale** [comment]
> We could automatically change the pulse proportions to match the behaviour in your second example---but I don't like this because altering the time by some epsilon then changes the behaviour.

Ah, you mentioned that option here. I guess it comes down to what we think the intended behavior of that would be. I think most users, if they define multiple pulses at once (for example, in the example I gave above), would be trying to specify (0.2, 0.3, 0.5) ancestry proportions.

**Comment by grahamgower** [comment]
This doesn't seem like it will be a commonly encountered scenario. Probably if a user wants to specify this, then they really do need to consider carefully why they want to do this, and probably rewrite their model as you described.

**Comment by molpopgen** [comment]
> @molpopgen Thinking forwards in time, if they are applied sequentially, say deme1 first, then the intermediate ancestry is 0.2/0.8. Then if you have 30% admixture from deme2, you'd have 0.2*(1-0.3) / 0.3 / 0.8 * (1-0.3) = 0.14 / 0.3 / 0.56 ancestry proportions. The other order has a different result.
> 
> A third option would be to say, if there are multiple pulses at once, we just treat it like an admixture event with proportions (0.2, 0.3, 1-0.2-0.3), which then gets placed in deme3. That would avoid having to decide on some arbitrary sorting, and would be easy to document.

To me, I see the third option that you define to be the natural one. That's why I don't immediately see the ambiguity. The way that I would implement this in fwdpy11 would be as a single generation change in the migration rates, using what you're calling the third option.

**Comment by grahamgower** [comment]
Ok, so what do you do if we instead have:
```yaml
pulses:
  - time: 9.99999
    source: deme1
    dest: deme3
    proportion: 0.2
  - time: 10
    source: deme2
    dest: deme3
    proportion: 0.3
```
And your conversion to integer generations makes both events occur simultaneously?
