### ISSUE TITLE
describe best-practices for specifying a demes graph

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#58]
E.g.

- for two extant populations, define (Ancestral, (child1, child2)), rather than (child1, (child1 continuation, child2).
- #46

**Comment by grahamgower** [comment]
Demes should be defined from the root(s) of the graph downwards. This is because when specifying a deme's ancestors, the ancestor demes must already have been defined.

**Comment by grahamgower** [comment]
I think it's clearer when yaml files use `start_time` rather than `end_time`. Sometimes using `start_time` more will result in a less compact definition, but I think that's fine.
E.g. in the docs we have (`docs/tutorial_examples/two_epoch.yaml`):
```
description: Single-population two-epoch demography.
time_units: generations
demes:
  Deme_name:
    description: A deme that doubles in size 100 generations ago.
    epochs:
    - initial_size: 1000
      end_time: 100
    - initial_size: 2000
      end_time: 0
```
Which I think would be clearer as (`/tmp/a.yml`):
```
description: Single-population two-epoch demography.
time_units: generations
demes:
  Deme_name:
    description: A deme that doubles in size 100 generations ago.
    initial_size: 1000
    epochs:
    - start_time: 100
      end_time: 0
      initial_size: 2000
```

It doesn't help that when we `dump()`, the output prefers `end_time`.
```
>>> import demes
>>> a = demes.load("/tmp/a.yml")
>>> b = demes.load("docs/tutorial_examples/two_epoch.yaml")
>>> a.isclose(b)
True
>>> print(demes.dumps(a))
description: Single-population two-epoch demography.
time_units: generations
demes:
  Deme_name:
    epochs:
    - end_time: 100
      initial_size: 1000
    - end_time: 0
      initial_size: 2000
    description: A deme that doubles in size 100 generations ago.
```

**Comment by grahamgower** [comment]
@apragsdale makes the very good point that "it makes more sense to specify end times in general and have derived demes inherit their start time from their ancestors, instead of having ancestors inherit end times from derived demes' start times. There's some notion of the flow of time that makes more sense in the first case, I think."

**Comment by apragsdale** [comment]
To summarize, since I think we're close to wrapping up these issues... there might be a few other details to work out, but I think this is one of the last major decisions: whether we require start times or end times to be specified for each epoch. In #133, we discuss requiring every epoch to be explicitly defined in the YAML. So within the epochs, we have the option that 1) end times for epochs inherit from the next epoch's start time or from the deme's successors, or 2) start times for epochs inherit from the previous epoch's end time or from the deme's predecessor.

As Graham mentioned, I'm a fan of the second case, as it fits better in the notion of the flow of time and "inheriting" from the parent. But just to illustrate the two, these would be the two cases:

1)
```YAML
demes:
- id: A
  epochs:
  - start_time: .inf
    initial_size: 100
  - start_time: 1000
    initial_size: 200
- id: B
  ancestors:
  - A
  epochs:
  - start_time: 200
    initial_size: 500
```

2)
```YAML
demes:
- id: A
  epochs:
  - initial_size: 100
    end_time: 1000
  - initial_size: 200
    end_time: 200
- id: B
  ancestors:
  - A
  epochs:
  - initial_size: 500
    end_time: 0
```

There's also the issue of how we write "inf" in the YAML (#130), and the second option avoids ever having to explicitly write that a start time is infinity. On the other hand, we need to write `end_time: 0` for all contemporary populations, instead of that being implied. I don't think that's too bad though, because it immediately lets a user see from the YAML which populations exist up until time zero instead and which are extinct populations. In the first case, you have to do some scanning of possible ancestors in the YAML to figure out if a population ends before present time or not. In the second case, it's explicit.

Anyway, that's some of my argument for specifying simplified demographies in the YAML :)
