### ISSUE TITLE
think about parameterised models

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#63]
Once the dust settles, we'll want to add more complexity. :P

Currently, demes deals with **concrete** demographic models, ie. those with fixed parameter values. It would be really neat if we could also support **parameterised** demographic models, where parameters have a distribution and optionally depend on other parameters (eg. for an upper or lower bound). The motivation here, is to draw values from the distribution for simulation, do parameter inference using the parameterised model as a prior, or even output an inferred posterior parameterised demographic model.

This would need at least: (1) additional syntax in the yaml file, (2) a dependency graph for the parameters, and (3) an internal representation of parameterised models, from which it is cheap to construct many concrete models. We should consider carefully the design of the current version of ``demes``, to avoid unnecessarily making this harder in the future.

**Comment by jeromekelleher** [comment]
Probably a good idea to sketch out what this might look like at the yaml level at least, as that'll be the hardest thing to change later.

**Comment by apragsdale** [comment]
Yes, I'm very excited to work toward that feature! Agree that we'll need to think a bit about how it looks at the YAML level and how to encode dependencies (as an auxiliary file or within the YAML, e.g.).

In the meantime though, maybe we should put together a milestone/checklist for `demes` version 1.0, to have a target for a note/paper and present to stdpopsim to get folks on board. I really think it's quite close.

**Comment by grahamgower** [comment]
How about having an additional `variables` stanza in the yaml, and permitting a variable name anywhere a numerical value is currently accepted? I imagine that a variable needs to have various properties such as : `description`, `distribution type`, `distribution parameters`, `upper bound`, `lower bound`. And we'll likely need to accept `expressions`, or the variables become overly restrictive.

```yaml
description: |
  Ancestral deme A suffers a bottleneck at time T_bottleneck, recovering 100 generations later.
  After the bottleneck, demes B and C split from A at time T_split.
  After the split, there is an admixture pulse from B into C at time T_pulse.
time_units: generations

variables:
  T_bottleneck:
    # Might want some shorthand for fixed variables (e.g. "T_bottleneck: 5000").
    description: start time for the bottleneck in deme A
    distribution:
      fixed: 5000
  T_split:
    description: time at which demes B and C split off from deme A
    distribution:
      # Distributions and parameters could be structured as nested fields.
      normal:
        mean: 2000
        stddev: 100
    # Specify upper and lower bounds, producing a truncated distribution.
    upper: T_bottleneck
    lower: 1000
  T_pulse:
    description: time of admixture pulse from deme B into deme C.
    distribution:
      # Distribution parameters could instead be a list (or we could permit both).
      uniform: [1, T_split]
    # T_pulse bounds are implied by uniform params; no need to set explicitly.

demes:
  A:
    initial_Size: 1000
    epochs:
      - start_time: T_bottleneck
        initial_size: 100
      # It seems likely we'll want to accept expressions wherever numerical
      # values are accepted, where expressions may also contain variables.
      - start_time: T_bottleneck + 100
        initial_size: 1000
  B:
    ancestors: A
    start_time: T_split
    initial_Size: 1000
  C:
    ancestors: A
    start_time: T_split
    initial_Size: 1000

pulse:
  source: B
  dest: C
  time: T_pulse
  proportion: 0.01

```

**Comment by jeromekelleher** [comment]
Feels like it'll be hard to get that to stick with yaml, and we'd end up embedding some sort of turing complete language into the description. Doing this in a semantically sensible way *across languages* would be really hard.

What if we considered each of the parameters to be an estimate, which by default are single point estimates. The model then is that the DemeGraph describes each parameter and its *distribution*. So, basically what you suggest except we embed the information about the distributions directly in line. I agree there's problems on how you deal with things like time periods that depend on the value of earlier times.

However, unless we go the whole hog and describe the model in something like [Lua](https://www.lua.org) we can't have arithmetic expressions. There's just no way we can imagine being able to support that in a C implementation of the demes parser.

**Comment by grahamgower** [comment]
> Feels like it'll be hard to get that to stick with yaml, and we'd end up embedding some sort of turing complete language into the description. Doing this in a semantically sensible way _across languages_ would be really hard.
> 

Yeah, supporting expressions does have problems, which is part of the reason I wanted to start thinking about it sooner rather than later (when it's much harder to change things). The expressions here will just become strings though, so this *should* be embeddable in yaml. I think.

> What if we considered each of the parameters to be an estimate, which by default are single point estimates. The model then is that the DemeGraph describes each parameter and its distribution. So, basically what you suggest except we embed the information about the distributions directly in line. I agree there's problems on how you deal with things like time periods that depend on the value of earlier times.
> 

I'm a little lost here. Any chance you can provide a small example? I suspect we really do need an approach that permits variables depending on other variables.

> However, unless we go the whole hog and describe the model in something like [Lua](https://www.lua.org) we can't have arithmetic expressions. There's just no way we can imagine being able to support that in a C implementation of the demes parser.

No, you're right. This definitely can't work in the yaml parser itself. But I really do think we want to have expressions *somehow*. Without this, the parameterised models are not worth having at all, because you can't even relate one variable to another by a constant. And once we permit simple expressions, then we almost certainly also want to permit a restricted set of functions like `log` and `exp`.

**Comment by jeromekelleher** [comment]
> I'm a little lost here. Any chance you can provide a small example?

```yaml
demes:
  A:
    initial_size: 1000 # single point estimate
  B:
    initial_size: # Or a distribution
        distribution:
            normal:
               mean: 2000
               stddev: 100
```

So, it's just what you said, except we embed the description of the distributions directly.

I'm *very* nervous about embedding any type of arithmetic or logic in here - all sorts of problems start popping up, which would take away the point of using yaml at all I think. This must be *declarative* and static, with simple and unambiguous semantics.

It seems to me that most of the need for expressions comes from time values - that time values later in the model are dependent on those chosen earlier. Would this be handled by allowing some way of stating time delta values rather than absolute times? Say, if a ``start_time`` value starts with "+" we consider it as an increment to the previous epoch's time? Like

```yaml
demes:
  A:
    initial_Size: 1000
    epochs:
      - start_time: Normal(2000, 100)   # Shorthand for value distribution above
        initial_size: 10
      - start_time: +100 # 100 units *after* the last epoch
        initial_size: 100
```

This level of complexity feels manageable to me. Although, I'd imagine the "+" syntax would make it easy to introduce bugs where someone means to write a relative time but they actually write an absolute time. Still, would allowing for relative time increments in some form resolve the need for global state and arithmetic operations?
