### ISSUE TITLE
Allow ancestor merge time to be flexible

### ISSUE THREAD

**Issue by apragsdale** [grahamgower/demes#7]
Right now, if I understand correctly, if a deme has an ancestor, it's end time has to be equal to the ancestors start time, so that ancestor and descendant populations cannot overlap. I think we want to relax this, and just check that the end time of a deme falls within the ancestors time interval.

As a very simple scenario, I'm imagining a demography that looks like the picture attached here, which has a main population and some offshoots. We don't want to have to set the three epochs along the main pop's branch as three separate demes.

From a user's perspective, I think we'd want the yaml description to look something like this. Then when reading it in, we'd validate that both end times of 500 and 1,000 are in [0, inf).

```YAML
description: An example demography with one main population that is unchanged, that
  spawns multiple offshoot populations.
time_units: generations
demes:
  - ancestral:
    description: Main population
    start_time: 0
    initial_size: 1000
  - offshoot1:
    description: More recent offshoot population
    ancestors: ancestral
    start_time: 0
    end_time: 500
    initial_size: 100
  - offshoot2:
    description: More ancient offshoot population
    ancestors: ancestral
    start_time: 0
    end_time: 1000
    initial_size: 200
```

![IMG_20200717_182949](https://user-images.githubusercontent.com/33734266/87886040-f4ce2380-c9e7-11ea-8b86-de2a9c64e42d.jpg)
