### ISSUE TITLE
demes without attributes

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#83]
If we use `default_Ne`, it's then possible to specify a deme without attributes, as all required attributes will be given sensible values. But the yaml syntax for an empty dictionary is not quite intuitive. Other attempts to do this will fail with syntax errors (e.g. `A:`, `- A` are incorrect).
```yaml
description: minimum reproducible example
time_units: years
default_Ne: 1000
demes:
  A: {}
```
```python
>>> print(*demes.load("/tmp/mre.yml").demes)
Deme(id='A', description=None, ancestors=None, proportions=None, epochs=[Epoch(start_time=inf, end_time=0, initial_size=1000, final_size=1000, size_function='constant', selfing_rate=None, cloning_rate=None)], selfing_rate=None, cloning_rate=None)
```
