### ISSUE TITLE
remove default_Ne?

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#89]
I'm not sure how useful having a `default_Ne` is in practice. I added it thinking that we might want to make it easy to add lots of demes with the same population size. Is this worth keeping it though (particularly in light of #83)?
```yaml
description: demorama
time_units: generations
default_Ne: 1000
demes:
  A: {}
  B: {}
  C: {}
  D: {}
  E: {}
  F: {}
migrations:
  symmetric:
    - demes: A, B, C, D, E, F
      rate: 1e-5
```
```yaml
description: demorama
time_units: generations
demes:
  A:
    initial_size: 1000
  B:
    initial_size: 1000
  C:
    initial_size: 1000
  D:
    initial_size: 1000
  E:
    initial_size: 1000
  F:
    initial_size: 1000
migrations:
  symmetric:
    - demes: A, B, C, D, E, F
      rate: 1e-5
```
